#!/usr/bin/env python3
"""Generate an InfernoVGPUMetalDevice ObjC stub conforming to MTLDevice +
MTLDeviceSPI from the ipsw class-dump output in this directory. Parses the
@property/method lines and emits a real, compilable (if minimally
functional) implementation: _Bool -> NO, integer types -> 0, id -> nil,
struct-returning -> zeroed struct via memset, void -> empty body. A small
hand-written set of "real" overrides (name, registryID, etc.) replaces the
generated stub for the handful of methods that matter for a device to even
show up sanely in system UI / basic queries.
"""
import re
import sys

PROP_RE = re.compile(r"@property\s*\(([^)]*)\)\s*(.+?)\s*\*?(\w+);")
METHOD_RE = re.compile(r"^([+-])\s*\(([^)]+)\)\s*(.+);$")

REAL_OVERRIDES = {
    "name",
    "registryID",
    "vendorName",
    "hasUnifiedMemory",
    "lowPower",
    "headless",
    "removable",
    "maxBufferLength",
    "recommendedMaxWorkingSetSize",
    "currentAllocatedSize",
}


def parse_file(path):
    props = []
    methods = []
    with open(path) as f:
        for line in f:
            line = line.strip()
            m = PROP_RE.search(line)
            if m:
                rtype = m.group(2).strip()
                name = m.group(3)
                props.append((rtype, name))
                continue
            m = METHOD_RE.match(line)
            if m:
                kind, rtype, rest = m.groups()
                methods.append((kind, rtype.strip(), rest))
    return props, methods


PARAM_RE = re.compile(r"(\w+):\(([^)]+)\)\s*(\w+)")


def objc_selector_and_params(rest):
    """Parse 'label1:(type1)name1 label2:(type2)name2' into [(label, type, name), ...].
    Zero-arg selectors (no ':') are returned as a bare string."""
    if ":" not in rest:
        return rest, None
    sel_pieces = [(m.group(1), m.group(2), m.group(3)) for m in PARAM_RE.finditer(rest)]
    return sel_pieces, None


def default_return(rtype):
    rtype = rtype.strip()
    if rtype in ("void",):
        return None
    if rtype == "_Bool":
        return "NO"
    if rtype.startswith("struct"):
        return "STRUCT"
    if rtype.endswith("*") or rtype == "id":
        return "nil"
    if "long long" in rtype or rtype in ("int", "unsigned int", "long", "unsigned long"):
        return "0"
    return "0"


# C/ObjC treat every syntactically-written `struct { ... }` as a *distinct*
# type, even if byte-for-byte identical to another occurrence elsewhere --
# so a method declared to return `struct { ... }` can't just declare a local
# variable re-typed the same way and return it ("incompatible result type").
# Fix: typedef each unique struct-return shape exactly once, and use that
# typedef consistently for both the method's declared return type and the
# local variable in its body.
STRUCT_TYPEDEFS = {}  # struct-text -> typedef name


def struct_typedef_name(struct_text):
    if struct_text not in STRUCT_TYPEDEFS:
        STRUCT_TYPEDEFS[struct_text] = f"InfernoStructRet{len(STRUCT_TYPEDEFS)}"
    return STRUCT_TYPEDEFS[struct_text]


def gen_method_stub(kind, rtype, rest, idx):
    zero_arg_name = rest if ":" not in rest else None
    if zero_arg_name in REAL_OVERRIDES:
        return ""

    ret_type_for_sig = rtype
    if rtype.startswith("struct"):
        ret_type_for_sig = struct_typedef_name(rtype)

    sel_pieces, last = objc_selector_and_params(rest)
    if isinstance(sel_pieces, str):
        # zero-arg method
        selector_decl = f"{kind} ({ret_type_for_sig}){sel_pieces}"
    else:
        decl_parts = []
        for label, ptype, pname in sel_pieces:
            decl_parts.append(f"{label}:({ptype}){pname}")
        selector_decl = f"{kind} ({ret_type_for_sig})" + " ".join(decl_parts)

    body_ret = default_return(rtype)
    if body_ret is None:
        body = ""
    elif body_ret == "STRUCT":
        body = f"{ret_type_for_sig} __r; memset(&__r, 0, sizeof(__r)); return __r;"
    else:
        body = f"return {body_ret};"
    return f"{selector_decl} {{ {body} }}\n"


def main():
    device_props, device_methods = parse_file("MTLDevice.txt")
    spi_props, spi_methods = parse_file("MTLDeviceSPI.txt")

    body_lines = []
    seen = set()
    n_methods = 0
    for props, methods in ((device_props, device_methods), (spi_props, spi_methods)):
        for rtype, name in props:
            seen.add(name)
        for kind, rtype, rest in methods:
            sel_key = rest.split(":")[0] if ":" in rest else rest
            if (kind, sel_key) in seen:
                continue
            seen.add((kind, sel_key))
            body_lines.append(gen_method_stub(kind, rtype, rest, n_methods))
            n_methods += 1

    out = []
    out.append("// AUTO-GENERATED by gen_stub.py from MTLDevice.txt + MTLDeviceSPI.txt.\n")
    out.append("// Every method/property not in REAL_OVERRIDES returns a safe zero/NO/nil\n")
    out.append("// default. This makes InfernoVGPUMetalDevice a structurally complete,\n")
    out.append("// loadable MTLDeviceSPI conformer -- Metal.framework should accept it as a\n")
    out.append("// device and be able to query capabilities without crashing, even though\n")
    out.append("// actual GPU work (buffers/textures/pipelines/command encoding) is not yet\n")
    out.append("// implemented -- those calls currently return nil/0, which callers must\n")
    out.append("// already handle (Metal API contracts allow allocation failure).\n\n")
    out.append("#import <Foundation/Foundation.h>\n")
    out.append("#import <Metal/Metal.h>\n")
    out.append('#import "InfernoVGPUMetalDevice.h"\n\n')

    out.append("// Struct-return typedefs -- see the comment above STRUCT_TYPEDEFS in gen_stub.py.\n")
    for struct_text, name in STRUCT_TYPEDEFS.items():
        out.append(f"typedef {struct_text} {name};\n")
    out.append("\n@implementation InfernoVGPUMetalDevice\n\n")
    out.extend(body_lines)
    out.append("\n@end\n")

    with open("InfernoVGPUMetalDevice_generated.m", "w") as f:
        f.writelines(out)

    print(f"generated {n_methods} method stubs, {len(STRUCT_TYPEDEFS)} struct typedefs")


if __name__ == "__main__":
    main()
