// Plain main()-based variant of inferno_widget_host.m -- see
// PROJECT_STATUS.md's "Widget-hosted Metal compositing: live test attempt
// (2026-07-31, new session)" dated update for why this variant exists.
//
// Live binary inspection of the REAL StocksWidget.appex/StocksWidget
// executable (done in that session, via the same dd+od / local Python
// Mach-O header parse used throughout this project) showed a genuine
// LC_MAIN with entryoff=0x4a658 -- i.e. dyld hands control to a normal
// compiled main() (almost certainly Swift's autogenerated top-level entry
// point for a @main-attributed WidgetBundle conformer, consistent with the
// real binary's LC_LOAD_DYLIB list: WidgetKit.framework, SwiftUI.framework,
// TeaUI.framework, TeaCharts.framework, TeaFoundation.framework,
// Stocks/StocksCore.framework, NewsFoundation.framework,
// Foundation.framework, libobjc.A.dylib) -- NOT the classic
// NSExtensionMain() bootstrap that inferno_widget_host.m (kept alongside
// this file, unmodified, for history/comparison -- same precedent as
// agx_system_metal_test_direct.m being kept alongside the dlsym-based
// rewrite of agx_system_metal_test.m) assumes. The Info.plist confirms the
// same thing from the metadata side: StocksWidget.appex/Info.plist's
// NSExtension dict has NSExtensionPointIdentifier =
// com.apple.widgetkit-extension and NO NSExtensionPrincipalClass key at
// all -- every widget .appex in this build (all 7 checked) is the same.
//
// This file fixes exactly that one, confirmed, architectural mismatch --
// nothing else. It does NOT attempt to replicate WidgetKit's real
// registration/timeline-provider protocol with its host process
// (WidgetKit.framework is DSC-resident and out of reach without the
// DSC-parser tooling being worked on elsewhere this session -- see this
// project's repeated "no ipsw/DSC-parser tooling" notes) -- this is
// explicitly, deliberately exploratory: get a plain-main()-shaped,
// non-instantly-exiting binary in place of StocksWidget's real executable
// and observe empirically how far it gets. Does it survive exec (past this
// project's 5 already-patched + 1 newly-patched SIGKILL-style gates, and
// past the separately-documented container-signature-cascade issue)? Does
// WidgetKit's own host process log anything once the immediate
// NSExtensionMain-shaped mismatch is gone? A well-documented "here's
// exactly how it fails now, and here's what that tells us" is a fully
// valid, valuable outcome per this task's own instructions -- matching
// this whole project's established standard of not forcing a
// false-positive conclusion.
//
// Structure, deliberately as simple/dependency-light as possible so any
// failure is attributable to *this file's own shape*, not incidental
// complexity: a real `int main(void)` -- no UIKit/UIViewController/CALayer
// at all. Without the NSExtensionMain/PlugInKit handshake this file
// specifically does NOT attempt, there is no host-provided view to draw
// into, so keeping that machinery around would add risk for zero payoff.
// Links only Foundation + Metal, mirroring this project's own already-
// proven-working plain executables (compute_test/draw_test, i.e.
// agx_metal_api_compute_test.m/agx_metal_api_draw_test.m), plus this
// project's own /b Metal bridge via dlopen. The render pipeline itself
// (same two AIR shaders, same call sequence: dlopen("/b") -> Q() -> device
// -> texture -> two MTLLibrarys -> pipeline -> queue -> per-frame
// buffer/encoder/draw/commit/getBytes) is reused here purely as an
// ongoing, self-checking signal that the process is alive and doing real
// work for as long as it survives -- not because this variant expects (or
// needs) any compositing to actually happen; there is no hosted CALayer
// for it to reach in this design. An infinite plain sleep()-paced loop
// (not CFRunLoopRun()/dispatch_main(), which would pull in run-loop
// bootstrap machinery this file has no need to depend on) is used
// deliberately, so it can't itself be the reason this process fails to
// stay alive.
#import <Foundation/Foundation.h>
#import <Metal/Metal.h>
#import <dlfcn.h>
#include <fcntl.h>
#include <unistd.h>
#include <string.h>
#include <math.h>
#include <stdio.h>

// Identical AIR text to inferno_widget_host.m's kInfernoVertAir/
// kInfernoFragAir (which is itself identical to the already-proven
// agx_metal_api_draw_test.m's kVertAir/kFragAir) -- deliberately NOT
// re-derived/simplified, to keep this file's rendering behavior
// byte-for-byte traceable back to the already-proven test.
static const char kVertAir[] =
    "source_filename = \"vertex_passthrough.metal\"\n"
    "target datalayout = \"e-p:64:64:64\"\n"
    "target triple = \"air64-apple-macosx14.0.0\"\n"
    "\n"
    "define <4 x float> @vmain(<4 x float> %position) local_unnamed_addr #0 {\n"
    "  ret <4 x float> %position\n"
    "}\n"
    "\n"
    "attributes #0 = { nounwind }\n"
    "\n"
    "!air.vertex = !{!0}\n"
    "!0 = !{ptr @vmain, !1, !2}\n"
    "!1 = !{!3}\n"
    "!2 = !{!4}\n"
    "!3 = !{!\"air.position\", !\"air.arg_type_name\", !\"float4\"}\n"
    "!4 = !{i32 0, !\"air.vertex_input\", !\"air.location_index\", i32 0, i32 1, "
    "!\"air.arg_type_name\", !\"float4\", !\"air.arg_name\", !\"position\"}\n";

static const char kFragAir[] =
    "source_filename = \"fragment_solid_red.metal\"\n"
    "target datalayout = \"e-p:64:64:64\"\n"
    "target triple = \"air64-apple-macosx14.0.0\"\n"
    "\n"
    "define <4 x float> @frag(<4 x float> %position) local_unnamed_addr #0 {\n"
    "  %r = insertelement <4 x float> undef, float 1.000000e+00, i64 0\n"
    "  %rg = insertelement <4 x float> %r, float 0.000000e+00, i64 1\n"
    "  %rgb = insertelement <4 x float> %rg, float 0.000000e+00, i64 2\n"
    "  %rgba = insertelement <4 x float> %rgb, float 1.000000e+00, i64 3\n"
    "  ret <4 x float> %rgba\n"
    "}\n"
    "\n"
    "attributes #0 = { nounwind }\n"
    "\n"
    "!air.fragment = !{!0}\n"
    "!0 = !{ptr @frag, !1, !2}\n"
    "!1 = !{!3}\n"
    "!2 = !{!4}\n"
    "!3 = !{i32 0, !\"air.render_target\", i32 0, i32 0, !\"air.arg_type_name\", !\"float4\"}\n"
    "!4 = !{i32 0, !\"air.position\", !\"air.center\", !\"air.arg_type_name\", !\"float4\"}\n";

// Diagnostic-only, same spirit as inferno_widget_host.m's WTrace and
// inferno_agx_bridge.m's QTrace -- deliberately a DIFFERENT log path
// (/tmp/widget_host_main_trace.log, not .../widget_host_trace.log) so a
// live test of this variant can never be confused with a stale log left
// over from an inferno_widget_host.m run. Each line is prefixed with the
// calling process's own pid, since -- if this ever actually gets launched
// as a real StocksWidget replacement -- there is no guarantee only one
// instance/attempt is ever made, and telling separate attempts apart
// matters for reading the log afterward.
static void WTrace(const char *msg)
{
    int fd = open("/tmp/widget_host_main_trace.log", O_WRONLY | O_CREAT | O_APPEND, 0666);
    if (fd < 0) {
        return;
    }
    char pidbuf[64];
    int n = snprintf(pidbuf, sizeof(pidbuf), "[pid %d] ", getpid());
    if (n > 0) {
        write(fd, pidbuf, (size_t)n);
    }
    write(fd, msg, strlen(msg));
    write(fd, "\n", 1);
    close(fd);
}

// File-scope (ARC-managed, implicitly __strong) globals -- kept alive for
// the whole process lifetime by the infinite loop in main(), same
// long-lived-object shape as inferno_widget_host.m's InfernoWidgetHost
// ivars, just without an enclosing ObjC object since there's no
// PlugInKit-provided instance to hang them off of here.
static id<MTLDevice> gDevice;
static id<MTLLibrary> gVertLib;
static id<MTLLibrary> gFragLib;
static id<MTLRenderPipelineState> gPipeline;
static id<MTLCommandQueue> gQueue;
static id<MTLTexture> gTarget;
static const NSUInteger kTexWidth = 64;
static const NSUInteger kTexHeight = 64;

// One-time setup, same shape/sequence as inferno_widget_host.m's
// -inferno_setUpDevice (see that file for the full step-by-step
// rationale) -- reproduced here as a plain C function since there is no
// enclosing ObjC instance in this variant.
static BOOL SetUpDevice(void)
{
    void *handle = dlopen("/b", RTLD_NOW);
    if (handle == NULL) {
        WTrace("SetUpDevice: dlopen(/b) failed");
        return NO;
    }
    void *(*fn)(void) = (void *(*)(void))dlsym(handle, "Q");
    void *raw = fn ? fn() : NULL;
    if (raw == NULL) {
        WTrace("SetUpDevice: Q() returned NULL");
        return NO;
    }
    gDevice = (__bridge id<MTLDevice>)raw;
    WTrace("SetUpDevice: got device");

    MTLTextureDescriptor *texDesc = [MTLTextureDescriptor
        texture2DDescriptorWithPixelFormat:MTLPixelFormatRGBA8Unorm
                                      width:kTexWidth height:kTexHeight mipmapped:NO];
    gTarget = [gDevice newTextureWithDescriptor:texDesc];
    if (gTarget == nil) {
        WTrace("SetUpDevice: newTextureWithDescriptor failed");
        return NO;
    }

    dispatch_data_t vertData = dispatch_data_create(
        kVertAir, sizeof(kVertAir) - 1,
        dispatch_get_main_queue(), DISPATCH_DATA_DESTRUCTOR_DEFAULT);
    dispatch_data_t fragData = dispatch_data_create(
        kFragAir, sizeof(kFragAir) - 1,
        dispatch_get_main_queue(), DISPATCH_DATA_DESTRUCTOR_DEFAULT);
    NSError *error = nil;
    gVertLib = [gDevice newLibraryWithData:vertData error:&error];
    gFragLib = [gDevice newLibraryWithData:fragData error:&error];
    if (gVertLib == nil || gFragLib == nil) {
        WTrace("SetUpDevice: newLibraryWithData failed");
        return NO;
    }

    id<MTLFunction> vertFn = [gVertLib newFunctionWithName:@"vmain"];
    id<MTLFunction> fragFn = [gFragLib newFunctionWithName:@"frag"];
    if (vertFn == nil || fragFn == nil) {
        WTrace("SetUpDevice: newFunctionWithName failed");
        return NO;
    }

    MTLRenderPipelineDescriptor *pDesc = [MTLRenderPipelineDescriptor new];
    pDesc.vertexFunction = vertFn;
    pDesc.fragmentFunction = fragFn;
    gPipeline = [gDevice newRenderPipelineStateWithDescriptor:pDesc error:&error];
    if (gPipeline == nil) {
        WTrace("SetUpDevice: newRenderPipelineStateWithDescriptor failed");
        return NO;
    }

    gQueue = [gDevice newCommandQueue];
    if (gQueue == nil) {
        WTrace("SetUpDevice: newCommandQueue failed");
        return NO;
    }
    WTrace("SetUpDevice: all objects built ok");
    return YES;
}

// Real per-frame work, same shape as inferno_widget_host.m's
// -inferno_renderAndPresent minus the final CGImage/CALayer.contents step
// (there is no hosted view to present into in this variant -- see the
// file-level comment above). Logs the first pixel's raw bytes each frame
// as a cheap, ongoing sanity signal that a real GPU round trip through
// this project's /b bridge is still succeeding for as long as this
// process survives.
static void RenderOneFrame(double phase, unsigned long frameIndex)
{
    if (gDevice == nil || gPipeline == nil || gQueue == nil || gTarget == nil) {
        return;
    }

    float dx = 0.35f * (float)sin(phase);
    float verts[3][4] = {
        {0.0f + dx, 0.6f, 0.0f, 1.0f},
        {-0.6f + dx, -0.6f, 0.0f, 1.0f},
        {0.6f + dx, -0.6f, 0.0f, 1.0f},
    };
    id<MTLBuffer> vbuf = [gDevice newBufferWithLength:sizeof(verts) options:0];
    if (vbuf == nil) {
        WTrace("RenderOneFrame: newBufferWithLength failed");
        return;
    }
    memcpy(vbuf.contents, verts, sizeof(verts));

    id<MTLCommandBuffer> cmdBuf = [gQueue commandBuffer];
    if (cmdBuf == nil) {
        WTrace("RenderOneFrame: commandBuffer failed");
        return;
    }

    MTLRenderPassDescriptor *passDesc = [MTLRenderPassDescriptor renderPassDescriptor];
    passDesc.colorAttachments[0].texture = gTarget;
    passDesc.colorAttachments[0].loadAction = MTLLoadActionClear;
    passDesc.colorAttachments[0].clearColor = MTLClearColorMake(0, 0, 0, 1);

    id<MTLRenderCommandEncoder> encoder = [cmdBuf renderCommandEncoderWithDescriptor:passDesc];
    if (encoder == nil) {
        WTrace("RenderOneFrame: renderCommandEncoderWithDescriptor failed");
        return;
    }
    [encoder setRenderPipelineState:gPipeline];
    [encoder setVertexBuffer:vbuf offset:0 atIndex:0];
    [encoder drawPrimitives:MTLPrimitiveTypeTriangle vertexStart:0 vertexCount:3];
    [encoder endEncoding];

    [cmdBuf commit];
    [cmdBuf waitUntilCompleted];

    NSUInteger bytesPerRow = kTexWidth * 4;
    static uint8_t pixels[64 /* kTexWidth */ * 4 * 64 /* kTexHeight */];
    [gTarget getBytes:pixels bytesPerRow:bytesPerRow
           fromRegion:MTLRegionMake2D(0, 0, kTexWidth, kTexHeight) mipmapLevel:0];

    char msg[160];
    snprintf(msg, sizeof(msg),
             "RenderOneFrame: frame %lu ok, pixel[0]=%02x%02x%02x%02x",
             frameIndex, pixels[0], pixels[1], pixels[2], pixels[3]);
    WTrace(msg);
}

// Real, plain, ordinary entry point -- exactly the shape the real
// StocksWidget binary's own LC_MAIN uses (a real compiled main(), not a
// dyld-stub-symbol entry override), and exactly the shape this project's
// own already-proven-working plain executables (compute_test/draw_test)
// already use. The very first statement writes a trace line before
// anything else runs, mirroring agx_system_metal_test.m's MTrace-as-first-
// statement pattern -- specifically so that even a total setup/render
// failure still leaves proof that execution reached user code at all,
// which matters here because "does it get further than the
// NSExtensionMain-shaped mismatch used to?" is this file's whole point.
int main(void)
{
    @autoreleasepool {
        char msg[64];
        snprintf(msg, sizeof(msg), "main: enter, pid=%d", getpid());
        WTrace(msg);
    }

    BOOL ready = NO;
    @autoreleasepool {
        ready = SetUpDevice();
        WTrace(ready ? "main: SetUpDevice succeeded, entering render loop"
                     : "main: SetUpDevice FAILED, entering idle loop (staying alive anyway)");
    }

    // Deliberately a plain sleep()-paced loop, not CFRunLoopRun()/
    // dispatch_main() -- see the file-level comment above for why. Runs
    // forever (this process is meant to BE the widget's executable for as
    // long as whatever launched it keeps it around); a periodic idle-tick
    // trace line fires even when SetUpDevice failed, so a live read of
    // /tmp/widget_host_main_trace.log can distinguish "process alive but
    // Metal setup failed" from "process never got this far at all".
    unsigned long frameIndex = 0;
    double phase = 0.0;
    for (;;) {
        @autoreleasepool {
            if (ready) {
                RenderOneFrame(phase, frameIndex);
                phase += 0.3;
            } else if (frameIndex % 10 == 0) {
                char msg[64];
                snprintf(msg, sizeof(msg), "main: idle tick %lu, still alive", frameIndex);
                WTrace(msg);
            }
        }
        frameIndex++;
        sleep(1);
    }
    return 0; // unreachable
}
